name: Build

on:
  push:
    branches:
      - master


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.cache
          key: ${{ runner.os }}-jdk11-${{ hashFiles('**/*.sbt') }}
          restore-keys: ${{ runner.os }}-jdk11-
      - name: Run Build
        run:  chmod +x ./docker/dockcross-android-arm64 && make linux-android-arm64